### ISSUE TITLE
Fork Feedback

### ISSUE THREAD

**Issue by maxbeatty** [MindscapeHQ/grunt-raygun-deployment#1]
First, congrats on launching the Deployments API. It's a great feature and we're excited to start using it.

We were also really happy to see a grunt plugin since we're big users of grunt. After reviewing the docs, a few things stuck out to me so I chose to [fork](https://github.com/maxbeatty/grunt-raygun-deployment). The changes I've made are pretty substantial. I don't think it makes sense to open a Pull Request, but I hope this general feedback helps others use one or the other to ultimately track deployments in raygun.

The first thing that stuck out to me is the configuring grunt with your application's API key and your personal external auth token. By making these options you define, you're implicitly encouraging developers to commit those keys and tokens into version control which is [a bad practice](http://12factor.net/config). Please correct me if I'm misguided about the sensitivity of the key or token.

The second thing that didn't jive with how we continuously release is the `Release.yml`. There's nothing wrong with this approach. It's nice that markdown is supported. We'd rather rely on git tags that link back to releases in GitHub which are most likely a merged Pull Request. I image both plugins will evolve to allow more customizations around this part.

Lastly, I wanted to have some tests. Grunt plugins are hard to unit tests because of their dependence on grunt and most plugins just rely on it running and checking the output. If and when this plugin evolves, I wanted to have more assurance everything should work as expected.

Hope this feedback is helpful. I wanted to contribute what I thought made sense upstream. Keep putting out APIs for us to hack on :neckbeard:

**Comment by jamiepenney** [comment]
Hi Max,

Thanks for the feedback! I agree it makes sense to fork given your changes - the beauty of having an open API is that it doesn't matter to me how the data gets in.

I agree that storing the personal auth token in source control isn't great. The API key is considered public knowledge (given there's no way to hide it in client side apps) and doesn't grant any privileges aside from the ability to pump errors reports into the system, so I'm not too concerned about keeping that out of source control. I'll look at copying your approach when I have a chance to work on the plugin again.

Using git tags is a good way of getting information for the deployment and something I'll look at. You could extract the git user and email for the `emailAddress` and `ownerName` fields in the deployment json, assuming it makes sense that the person who merges the pull request "owns" the deployment.

Thanks for your contribution, even if it's not to this package directly. Always good to hear how people are using our work!

Cheers,
Jamie
