### ISSUE TITLE
Javascript Error on deployments panel

### ISSUE THREAD

**Issue by indrajeet-ambadekar** [MindscapeHQ/grunt-raygun-deployment#2]
![screen shot 2015-05-11 at 8 33 33 pm](https://cloud.githubusercontent.com/assets/6253334/7567897/557bc68a-f81d-11e4-80c8-e73a0e6bf794.png)

I was testing deployments tracking for my project using your grunt task, and it completed without any error. But on my deployments list panel on raygun dashboard, i get a blank view. i have attached the snapshot of my browser console

**Comment by jamiepenney** [comment]
Hi Indrajeet,

This wasn't a problem with the grunt task, it was a problem with the new graph we added to the deployments page. It should be fixed now.

Cheers,
Jamie
